ApplyGoing, ApplyGoingLog and ApplyGoingDocActivity
DSM-DMS/DMS-Android-V3 pull request #9
Opened 2019-02-09 18:10 UTC by jinusong

진짜로 빡코딩했으면 진작에 끝났을 것을 제가 너무 질질끌면서 했네요... 죄송합니다....
코드는 전체적으로 구조에 맞도록 노력해서 짰지만 별로 보기에 좋지 않은 코드들이라서 안타깝네요
LiveData를 좀 더 활용하고 싶었으나 LiveData가 계속 null 값으로 변하는 심각한 오류를 1주일동안 겪어서
어쩔 수 없이 LiveData 대신 Intent를 활용했습니다.....

결론: 매우 아쉽네여

2019-02-13 15:47 UTC, jinusong commented
ApplyStayingActivity는 그냥 ApplyGoingActivity와 속성이 비슷해서 같은 브런치에 커밋하였습니다.
ApplyStayingActivity를 얼추 다하긴했는데 View의 이벤트를 처리하는 과정에서 일부 버그가 발생합니다.
나름대로 고민을 했는데 도무지 해결이 되지 않아서 혼자 생각하는 것보단 여럿이 좋겠다고 생각해서 
이렇게 그냥 올렸습니다. ApplyStayingActivity의 버그 픽스를 부탁드립니다 (ViewGroup의 child가 3개밖에 인식이 안됩니다. ApplyStayingViewModel의 17번째 줄입니다.)

2019-02-14 11:59 UTC, papered requested changes
👍

2019-02-14 12:06 UTC, papered approved these changes

2019-02-14 12:48 UTC, PaperEd commented on .idea/codeStyles/Project.xml
> -    <AndroidXmlCodeStyleSettings>
ㅜㅜ 이거 빼지 말아주세요

2019-02-14 12:48 UTC, PaperEd commented on app/src/main/res/layout/activity_apply_going.xml
> +        <android.support.design.widget.AppBarLayout
constraint 걸어주는게 좋을 것 같아요

2019-02-14 12:53 UTC, PaperEd commented
`applyGoing` 패키지에 다 넣지 말고 `applyGoingDoc` 패키지 만들어서 분리시키는게 통일성 있을 것 같아요!~~

2019-02-14 14:00 UTC, jinusong commented on .idea/codeStyles/Project.xml
> -    <AndroidXmlCodeStyleSettings>
커밋할 때 잘못 올렸네요...

2019-02-14 15:28 UTC, jinusong commented on app/src/main/res/layout/activity_apply_going.xml
> +        <android.support.design.widget.AppBarLayout
딱히 문제는 없었다면 고치겠습니다

2019-02-14 15:30 UTC, jinusong commented
외출신청 리팩토링했습니다

2019-02-15 10:58 UTC, PaperEd commented on app/src/main/res/layout/activity_apply_going.xml
> +        <android.support.design.widget.AppBarLayout
사실 별 문제 없겠지만 제가 빨간줄보면 불편해해성..ㅎㅎ

2019-02-15 13:52 UTC, PaperEd commented on app/src/main/java/dsm/android/v3/ui/applyStaying/ApplyStayingActivity.kt
> +            view.find<TextView>(R.id.item_applyStaying_title_tv).text = models.get(position).week
```suggestion
            view.find<TextView>(R.id.item_applyStaying_title_tv).text = models[position].week
```
이게 더 보기 깔끔할거같아요~~~

2019-02-15 14:31 UTC, jinusong commented on app/src/main/java/dsm/android/v3/ui/applyStaying/ApplyStayingActivity.kt
> +            view.find<TextView>(R.id.item_applyStaying_title_tv).text = models.get(position).week
^오^b

2019-02-18 14:18 UTC, juyonglee79 approved these changes

2019-03-01 08:31 UTC, jinusong commented
Resolve 해결하려고 API랑 MyPageFragment를 수정했습니다 mater에 추가하겠습니다

2019-03-01 08:34 UTC, jinusong commented
다른 브렌치를 파서 풀리퀘를 해야되지만 릴리즈까지 시간이 얼마 남지 않았고 브렌치 꼬일까봐 그냥 이 브렌치에 커밋했습니다. 그리고 코드를 보면 BindingAdapter가 필요한 부분이 있는데 종현이형 코드보니까 이미 ViewPager관련 BindingAdapter가 있어서 굳이 추가하지는 않았습니다. 아무튼 그렇습니당

2019-03-01 11:08 UTC, papered approved these changes

2019-03-01 11:08 UTC, papered commented on app/src/main/java/dsm/android/v3/ui/mypage/MyPageInfoModel.kt
> +    @SerializedName("badPoint")
변수 이름이랑 Response로 오는 json 키값 같으면 `@SerializedName()` 안써줘도 돼요!~~

2019-03-01 11:08 UTC, PaperEd commented on app/src/main/java/dsm/android/v3/ui/applyExtensionStudy/ExtensionModel.kt
> +data class ExtensionModel(@SerializedName("map") var map: ArrayList<ArrayList<Any>>)
변수 이름이랑 Response로 오는 json 키값 같으면 `@SerializedName()` 안써줘도 돼요!~~

2019-03-01 11:08 UTC, PaperEd commented on app/src/main/java/dsm/android/v3/ui/applyStaying/ApplyStayingModel.kt
> +data class ApplyStayingModel(@SerializedName("value") var value: Int)
변수 이름이랑 Response로 오는 json 키값 같으면 `@SerializedName()` 안써줘도 돼요!~~

2019-03-01 11:11 UTC, papered approved these changes

2019-03-01 11:11 UTC, PaperEd commented on app/src/main/java/dsm/android/v3/ui/logOutDialog/LogoutDialogFragmenet.kt
> +class LogoutDialogFragmenet: DataBindingDialogFragment<DialogLogoutBinding>(), LogOutContract {
?오타남 ㅋㅋ

2019-03-01 11:12 UTC, PaperEd commented
오 굳굳 저번보다 더 깔끔해진거같네요

2019-03-01 12:30 UTC, jinusong commented on app/src/main/java/dsm/android/v3/ui/logOutDialog/LogoutDialogFragmenet.kt
> +class LogoutDialogFragmenet: DataBindingDialogFragment<DialogLogoutBinding>(), LogOutContract {
오타요???

2019-03-01 12:30 UTC, jinusong commented on app/src/main/java/dsm/android/v3/ui/applyStaying/ApplyStayingModel.kt
> +data class ApplyStayingModel(@SerializedName("value") var value: Int)
네

2019-03-01 13:19 UTC, PaperEd commented on app/src/main/java/dsm/android/v3/ui/logOutDialog/LogoutDialogFragmenet.kt
> +class LogoutDialogFragmenet: DataBindingDialogFragment<DialogLogoutBinding>(), LogOutContract {
`LogoutDialogFragmenet`
Frag**menet**?

2019-03-01 13:32 UTC, jinusong commented on app/src/main/java/dsm/android/v3/ui/logOutDialog/LogoutDialogFragmenet.kt
> +class LogoutDialogFragmenet: DataBindingDialogFragment<DialogLogoutBinding>(), LogOutContract {
A...HA......

2019-03-01 13:33 UTC, jinusong commented on app/src/main/java/dsm/android/v3/ui/applyStaying/ApplyStayingModel.kt
> +data class ApplyStayingModel(@SerializedName("value") var value: Int)
근데 SerializedName 어노테이션이 명시적인 역할도 하는 것같은데 그냥 나둬도 될까요?

2019-03-02 02:49 UTC, PaperEd commented on app/src/main/java/dsm/android/v3/ui/applyStaying/ApplyStayingModel.kt
> +data class ApplyStayingModel(@SerializedName("value") var value: Int)
아 그런가
사실 별 지장 없으니까 걍 놔두고 싶으면 놔둬도 될듯 ㅋㅋ

2019-03-02 14:06 UTC, PaperEd commented on app/src/main/java/dsm/android/v3/ui/applyGoing/ApplyGoingDataModel.kt
> +        data class ApplyGoingDataModel(
요상괴상한 오류나는이유: `ApplyGoingDataModel` 안에 `ApplyGoingDataModel`이 또 있기 때문
안에있는 클래스 이름 바꾸면 해결됨

2019-03-17 05:16 UTC, merged